# Generated by Django 4.0.4 on 2022-05-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_movie_description_movie_imdb_rating_movie_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.CharField(default='', max_length=10),
        ),
    ]
