# Generated by Django 4.0.4 on 2022-05-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_movie_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, default=2000)),
                ('description', models.TextField(default='')),
                ('imdb_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='Django-Project-Assets')),
                ('category', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
