# Generated by Django 4.0.4 on 2022-05-19 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_serie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie',
            name='imdb_rating',
        ),
    ]
