# Generated by Django 4.0.4 on 2022-05-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_serie_imdb_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('lastname', models.CharField(blank=True, max_length=64)),
                ('movies', models.ManyToManyField(to='main.movie')),
                ('series', models.ManyToManyField(to='main.serie')),
            ],
        ),
    ]
