# Generated by Django 4.0.4 on 2022-05-20 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_actor_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='category',
            new_name='universe',
        ),
    ]
