# Generated by Django 4.0.4 on 2022-05-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_category_actor_universe'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='Django-Project-Assets'),
        ),
    ]
