# Generated by Django 4.0.4 on 2022-05-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_actor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='age',
            field=models.PositiveSmallIntegerField(default=20, unique=True),
        ),
    ]
