# Generated by Django 4.0.4 on 2022-05-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_actor_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='character',
            field=models.CharField(default='', max_length=64),
        ),
    ]
